#!/usr/bin/env bash
# Regenerate the schedule inventory — everything that runs on a timer, anywhere.
#
#   ~/bin/schedule-inventory.sh          write the manifest
#   ~/bin/schedule-inventory.sh --print  print it, write nothing
#
# WHERE IT WRITES, AND WHY THERE. ~/repo-tools/manifests/ already holds
# ACTIVE_SCRIPTS.md and FINAL_SCRIPT_ESTATE_INVENTORY.txt -- inventories of what
# exists across the estate. A schedule inventory is the same kind of artefact
# and belongs beside them rather than loose in the home folder.
#
# ~/SCHEDULE.md is left as a SYMLINK to it, which is the shortcut pattern
# already in use in the home folder (update_lkg_from_zip.sh and friends point
# into repo-tools/active the same way). One canonical file, one obvious place
# to look.
#
# LIVES IN ~/bin, NOT IN A REPO. It describes launchd agents and the scheduled
# workflows of THIRTEEN repos; how-we-know is one of them and has no more claim
# to the inventory than the others. Keeping it here also keeps how-we-know's
# own guards honest -- V30 correctly flagged a cross-repo script sitting in
# bin/ as an untracked lane entrypoint, which is exactly what it was.
#
# WHY A SCRIPT AND NOT A TYPED LIST. A hand-written inventory of scheduled jobs
# is wrong within a week and nobody notices, because the thing it describes runs
# whether or not the page agrees. This reads the launchd plists, the crontab and
# every repo's .github/workflows on this machine, so the page cannot drift
# without the generator drifting with it.
#
# It covers EVERY repo under ~/GitHub, not just this one. A cross-repo schedule
# has no better home, and the jobs compete for the same Mac.
set -uo pipefail
cd "$HOME" || { echo "NAMED STOP [NO_HOME] cannot enter \$HOME; refusing to write a manifest from an unknown directory."; exit 3; }
OUT="$HOME/repo-tools/manifests/SCHEDULE.md"
mkdir -p "$(dirname "$OUT")"
PRINT_ONLY=0
[ "${1:-}" = "--print" ] && PRINT_ONLY=1

python3 - "$PRINT_ONLY" "$OUT" <<'PYEOF'
import datetime, glob, os, plistlib, re, subprocess, sys, pathlib

print_only, out_path = sys.argv[1] == "1", sys.argv[2]
HOME = pathlib.Path.home()
L = []

def sh(*a):
    return subprocess.run(a, capture_output=True, text=True).stdout

# Local offset now, stated rather than assumed -- a UTC cron read as local is
# the single easiest way to get one of these tables wrong.
now = datetime.datetime.now().astimezone()
off = int(now.utcoffset().total_seconds() // 3600)
tz = now.tzname()

DAYS = {"0": "Sun", "1": "Mon", "2": "Tue", "3": "Wed", "4": "Thu",
        "5": "Fri", "6": "Sat", "7": "Sun"}

def local_of(minute, hour, dom, mon, dow):
    """A UTC cron field set rendered in local time. Only handles the shapes
    this repo actually uses; anything else is passed through verbatim rather
    than guessed at."""
    if not hour.isdigit() or not minute.isdigit():
        return "—"
    h = (int(hour) + off) % 24
    shifted = (int(hour) + off) // 24        # -1 or 0 for a day roll-back
    when = f"{h:02d}:{int(minute):02d}"
    if dow != "*":
        names = []
        for part in dow.split(","):
            if "-" in part:
                a, b = part.split("-")
                if a.isdigit() and b.isdigit():
                    names.append("-".join((DAYS.get(a, a), DAYS.get(b, b))))
                    continue
            names.append(DAYS.get(part, part))
        # A UTC hour that rolls back past midnight lands on the PREVIOUS day
        # locally. Saying "Sat 23:00" for a Saturday-04:00-UTC cron would be
        # wrong by a full day in the direction that matters -- someone waiting
        # up for it on the wrong night.
        if shifted:
            back = {"Sun": "Sat", "Mon": "Sun", "Tue": "Mon", "Wed": "Tue",
                    "Thu": "Wed", "Fri": "Thu", "Sat": "Fri"}
            names = [back.get(n, n) for n in names]
        day = ",".join(names)
        return f"{day} {when}"
    if dom != "*":
        return f"{dom}{'st' if dom=='1' else 'th'} {when}"
    return f"daily {when}"

L += [f"# Everything that runs on a timer",
      "",
      f"*Generated by `~/bin/schedule-inventory.sh` on "
      f"{now:%Y-%m-%d %H:%M} {tz}. Re-run it rather than editing this file — "
      f"a hand-kept list of scheduled jobs is wrong within a week and nothing "
      f"tells you.*",
      "",
      f"Local times are {tz} (UTC{off:+d}).",
      ""]

# ------------------------------------------------------------------ launchd
L += ["## On this Mac — launchd", ""]
rows = []
for p in sorted(glob.glob(str(HOME / "Library/LaunchAgents/*.plist"))):
    label = os.path.basename(p)[:-6]
    if not (label.startswith("com.howweknow") or label.startswith("com.seq")):
        continue                      # third-party updaters are not ours
    try:
        d = plistlib.load(open(p, "rb"))
    except Exception:
        continue
    sci = d.get("StartCalendarInterval")
    when = []
    for e in (sci if isinstance(sci, list) else [sci] if sci else []):
        wd = DAYS.get(str(e["Weekday"]), "") if "Weekday" in e else ""
        when.append(f"{wd} {e.get('Hour',0):02d}:{e.get('Minute',0):02d}".strip())
    if "WatchPaths" in d:
        when.append("on change: " + ", ".join(
            x.replace(str(HOME), "~") for x in d["WatchPaths"]))
    if not when and d.get("StartInterval"):
        when.append(f"every {d['StartInterval']}s")
    cmd = " ".join(d.get("ProgramArguments", []))
    m = re.search(r"(\S+\.sh)", cmd)
    runs = (m.group(1).replace(str(HOME), "~") if m else cmd[:60]) or "—"
    st = sh("launchctl", "list")
    line = next((l for l in st.splitlines() if l.endswith(label)), "")
    pid, last = (line.split()[0], line.split()[1]) if line else ("-", "?")
    status = ("running" if pid.isdigit()
              else f"last exit {last}" if last not in ("0", "?")
              else "ok")
    rows.append((", ".join(when) or "manual", label, runs, status))

L += ["| When (local) | Agent | Runs | Status |", "|---|---|---|---|"]
for w, lab, runs, st in sorted(rows):
    L.append(f"| {w} | `{lab}` | `{runs}` | {st} |")
L.append("")

cron = sh("crontab", "-l").strip()
L += [f"**crontab:** {'see below' if cron else 'empty — everything here is launchd.'}", ""]
if cron:
    L += ["```", cron, "```", ""]

# ------------------------------------------------------- GitHub Actions
L += ["## In the cloud — GitHub Actions", ""]
gh = HOME / "GitHub"
per_repo = {}
for repo in sorted(os.listdir(gh)) if gh.is_dir() else []:
    # A GIT WORKTREE IS NOT A REPO. ~/GitHub holds .hwk-wt-reach and
    # .hwk-wt-stops, both worktrees of how-we-know, and counting them listed
    # this repo's eleven lanes three times and inflated the total from 71 to
    # 93. A worktree's `.git` is a FILE pointing at the parent, not a
    # directory, which is the reliable way to tell them apart.
    d = gh / repo
    if repo.startswith(".") or (d / ".git").is_file():
        continue
    wf = d / ".github" / "workflows"
    if not wf.is_dir():
        continue
    found = []
    for f in sorted(list(wf.glob("*.yml")) + list(wf.glob("*.yaml"))):
        text = f.read_text(errors="ignore")
        name = next((l.split(":", 1)[1].strip()
                     for l in text.splitlines() if l.startswith("name:")), f.stem)
        for c in re.findall(r"cron:\s*['\"]?([^'\"\n]+)", text):
            parts = c.split()
            if len(parts) != 5:
                continue
            found.append((c.strip(), local_of(*parts), name))
    if found:
        per_repo[repo] = found

total = sum(len(v) for v in per_repo.values())
L += [f"**{total} scheduled workflows across {len(per_repo)} repos.** They all "
      f"run on GitHub's clock, not this Mac's — the machine can be asleep.", ""]

for repo, found in sorted(per_repo.items(), key=lambda kv: (kv[0] != "how-we-know", kv[0])):
    L += [f"### {repo} ({len(found)})", "",
          "| UTC | Local | Lane |", "|---|---|---|"]
    for c, loc, name in sorted(found, key=lambda x: x[1]):
        L.append(f"| `{c}` | {loc} | {name} |")
    L.append("")

L += ["---", "",
      "## Reading this",
      "",
      "- **launchd runs only while she is logged in.** After a reboot, log in "
      "rather than leaving the Mac at the login window, or nothing on the first "
      "table fires.",
      "- **A `last exit 3` is a NAMED STOP**, not a crash — a lane halting "
      "deliberately. `loop/state/stops/` says which condition, and the Sunday "
      "digest reports it.",
      "- **The cloud lanes do not need this Mac.** Only narration and rendering "
      "are local, by necessity.",
      ""]

body = "\n".join(L)
if print_only:
    print(body)
else:
    pathlib.Path(out_path).write_text(body)
    # The home-folder shortcut is refreshed every run, so it can never point at
    # a file a previous layout left behind.
    link = pathlib.Path.home() / "SCHEDULE.md"
    if link.is_symlink() or link.exists():
        link.unlink()
    link.symlink_to(out_path)
    print(f"wrote {out_path}")
    print(f"  {total} cloud workflows, {len(rows)} launchd agents")
    print(f"  ~/SCHEDULE.md -> {out_path.replace(str(pathlib.Path.home()), '~')}")
PYEOF
